- hosts: all
  vars:
    app_path: /home/ubuntu/gluto
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson

  tasks:

    - name: include vault vars
      include_vars: token.yml

    - name: install base soft
      become: true
      apt:
        name: git
        update_cache: true

    - name: add node 4.x source
      become: true
      shell: "curl -sL https://deb.nodesource.com/setup_4.x | bash -"

    - name: install node 4.x
      become: true
      apt:
        name: nodejs
        update_cache: true

    - name: add gluto systemd service
      become: true
      template: src=gluto_systemd dest=/etc/systemd/system/gluto.service

    - name: pull gluto
      git: repo=https://github.com/inirudebwoy/gluto dest={{ app_path }}

    - name: npm install
      npm: path={{ app_path }}

    - name: copy runner
      template: src=run.sh dest={{ app_path }}/run.sh mode=ug=rwx

    - name: start gluto
      become: true
      service: name=gluto state=started enabled=yes
