# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "ansible" do |ansible|
    ansible.ask_vault_pass = true
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
